language: cpp
    
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package testthat
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - CXX1X="g++-4.8" CXX1XSTD="-std=c++11" 
  
script:
  - R CMD INSTALL .
  - cd ..
  - git clone https://github.com/Rcpp11/Rcpp-test.git
  - git clone https://github.com/Rcpp11/attributes.git
  - R CMD INSTALL attributes
  - Rscript -e "library('attributes'); compileAttributes('Rcpp-test')"
  - R CMD INSTALL --install-tests Rcpp-test
  - Rscript -e "require(methods); require(RcppTest); require(testthat); require(devtools); test_package('RcppTest')"
  
notifications:
  email:
    on_success: change
    on_failure: change

